export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const EMPTY_CART = "EMPTY_CART"

export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY"

export const WISHLIST_ADD = "WISHLIST_ADD"
export const WISHLIST_REMOVE = "WISHLIST_REMOVE"

export const PRODUCT_LIST = "PRODUCT_LIST"
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST"


